[package]
name = "loadgen"
version = "0.1.0"
edition = "2021"

[lib]
name = "loadgen"
path = "src/lib.rs"

[[bin]]
name = "loadgen"
path = "src/main.rs"

[dependencies]
protocol = { path = "../protocol" }
tokio = { workspace = true }
tonic = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
